// Generated by `wit-bindgen` 0.11.0. DO NOT EDIT!
#include "url_shortener.h"


typedef struct {
  bool is_some;
  url_shortener_string_t val;
} url_shortener_option_string_t;

__attribute__((__import_module__("wasi:cli/environment"), __import_name__("get-environment")))
void __wasm_import_wasi_cli_environment_get_environment(int32_t);

__attribute__((__import_module__("wasi:cli/environment"), __import_name__("get-arguments")))
void __wasm_import_wasi_cli_environment_get_arguments(int32_t);

__attribute__((__import_module__("wasi:cli/environment"), __import_name__("initial-cwd")))
void __wasm_import_wasi_cli_environment_initial_cwd(int32_t);
__attribute__((__weak__, __export_name__("cabi_post_golem:template/api#get")))
void __wasm_export_exports_golem_template_api_get_post_return(int32_t arg0) {
  if ((*((int32_t*) (arg0 + 4))) > 0) {
    free((void*) (*((int32_t*) (arg0 + 0))));
  }
}

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

// Helper Functions

void url_shortener_tuple2_string_string_free(url_shortener_tuple2_string_string_t *ptr) {
  url_shortener_string_free(&ptr->f0);
  url_shortener_string_free(&ptr->f1);
}

void url_shortener_list_tuple2_string_string_free(url_shortener_list_tuple2_string_string_t *ptr) {
  for (size_t i = 0; i < ptr->len; i++) {
    url_shortener_tuple2_string_string_free(&ptr->ptr[i]);
  }
  if (ptr->len > 0) {
    free(ptr->ptr);
  }
}

void url_shortener_list_string_free(url_shortener_list_string_t *ptr) {
  for (size_t i = 0; i < ptr->len; i++) {
    url_shortener_string_free(&ptr->ptr[i]);
  }
  if (ptr->len > 0) {
    free(ptr->ptr);
  }
}

void url_shortener_string_set(url_shortener_string_t *ret, const char*s) {
  ret->ptr = (char*) s;
  ret->len = strlen(s);
}

void url_shortener_string_dup(url_shortener_string_t *ret, const char*s) {
  ret->len = strlen(s);
  ret->ptr = (char*) cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void url_shortener_string_free(url_shortener_string_t *ret) {
  if (ret->len > 0) {
    free(ret->ptr);
  }
  ret->ptr = NULL;
  ret->len = 0;
}

// Component Adapters

__attribute__((__aligned__(4)))
static uint8_t RET_AREA[8];

void wasi_cli_environment_get_environment(url_shortener_list_tuple2_string_string_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[8];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_cli_environment_get_environment(ptr);
  *ret = (url_shortener_list_tuple2_string_string_t) { (url_shortener_tuple2_string_string_t*)(*((int32_t*) (ptr + 0))), (size_t)(*((int32_t*) (ptr + 4))) };
}

void wasi_cli_environment_get_arguments(url_shortener_list_string_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[8];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_cli_environment_get_arguments(ptr);
  *ret = (url_shortener_list_string_t) { (url_shortener_string_t*)(*((int32_t*) (ptr + 0))), (size_t)(*((int32_t*) (ptr + 4))) };
}

bool wasi_cli_environment_initial_cwd(url_shortener_string_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[12];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_cli_environment_initial_cwd(ptr);
  url_shortener_option_string_t option;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      option.is_some = false;
      break;
    }
    case 1: {
      option.is_some = true;
      option.val = (url_shortener_string_t) { (char*)(*((int32_t*) (ptr + 4))), (size_t)(*((int32_t*) (ptr + 8))) };
      break;
    }
  }
  *ret = option.val;
  return option.is_some;
}

__attribute__((__export_name__("golem:template/api#get")))
int32_t __wasm_export_exports_golem_template_api_get(void) {
  url_shortener_string_t ret;
  exports_golem_template_api_get(&ret);
  int32_t ptr = (int32_t) &RET_AREA;
  *((int32_t*)(ptr + 4)) = (int32_t) (ret).len;
  *((int32_t*)(ptr + 0)) = (int32_t) (ret).ptr;
  return ptr;
}

__attribute__((__export_name__("golem:template/api#stats")))
int64_t __wasm_export_exports_golem_template_api_stats(void) {
  uint64_t ret = exports_golem_template_api_stats();
  return (int64_t) (ret);
}

extern void __component_type_object_force_link_url_shortener(void);
void __component_type_object_force_link_url_shortener_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_url_shortener();
}
